baseURL = 'https://example.org/'
languageCode = 'zh-cn'
title = 'Devflow'
theme = "hugo-book"
[markup]
  [markup.goldmark.renderer]
    unsafe = true
relativeURLs = true
[params]
   BookTheme = 'auto'
   BookToC = false
   BookSection = 'docs'
   BookDateFormat = '2006-01-02'
   BookSearch = false
   BookComments = false
   weight = 20
   bookHidden = false
